markets:
  sp500:
    market: S&P 500
    symbols:
      - AAPL
      - MSFT
      - NVDA
      - AMZN
      - GOOGL
      - GOOG
      - META
      - BRK-B
      - AVGO
      - TSLA
      - JPM
      - LLY
      - V
      - XOM
      - MA
      - UNH
      - COST
      - WMT
      - PG
      - NFLX
      - JNJ
      - HD
      - ABBV
      - BAC
      - KO
      - PLTR
      - ORCL
      - CRM
      - CSCO
      - AMD
      - CVX
      - WFC
      - IBM
      - GE
      - PM
      - ABT
      - MCD
      - LIN
      - MRK
      - DIS
      - NOW
      - T
      - ACN
      - ISRG
      - INTU
      - GS
      - VZ
      - TXN
      - QCOM
      - PEP
      - BKNG
      - RTX
      - CAT
      - SPGI
      - AXP
      - MS
      - AMGN
      - LOW
      - NEE
      - PGR
      - HON
      - BLK
      - AMAT
      - TJX
      - DHR
      - UNP
      - BSX
      - SYK
      - GILD
      - SCHW
      - DE
      - ADP
      - CMCSA
      - PANW
      - C
      - LRCX
      - ETN
      - ADI
      - MMC
      - COP
      - CB
      - KLAC
      - MU
      - MDLZ
      - UPS
      - BMY
      - SO
      - ANET
      - ELV
      - FI
      - SBUX
      - PLD
      - ICE
      - SHW
      - MO
      - WM
      - CVS
      - APH
      - CDNS
      - SNPS
  nasdaq:
    market: Nasdaq
    symbols:
      - NVDA
      - MSFT
      - AAPL
      - AMZN
      - AVGO
      - META
      - TSLA
      - GOOGL
      - GOOG
      - NFLX
      - COST
      - AMD
      - PLTR
      - CSCO
      - TMUS
      - LIN
      - PEP
      - ISRG
      - INTU
      - QCOM
      - BKNG
      - AMGN
      - TXN
      - AMAT
      - HON
      - PANW
      - ADI
      - LRCX
      - GILD
      - CMCSA
      - ADP
      - MU
      - KLAC
      - MELI
      - SBUX
      - CDNS
      - SNPS
      - MDLZ
      - CTAS
      - CRWD
      - MAR
      - ORLY
      - CSX
      - FTNT
      - PYPL
      - REGN
      - ABNB
      - NXPI
      - MNST
      - MSTR
      - WDAY
      - ROP
      - AEP
      - ADSK
      - PCAR
      - KDP
      - EXC
      - FAST
      - PAYX
      - AXON
      - CEG
      - TEAM
      - DDOG
      - XEL
      - IDXX
      - EA
      - BKR
      - ODFL
      - VRSK
      - GEHC
      - CCEP
      - LULU
      - FANG
      - CTSH
      - DXCM
      - BIIB
      - GFS
      - ON
      - ANSS
      - CDW
      - ZS
      - MDB
      - WBD
      - MCHP
      - TTWO
      - ILMN
      - MRVL
      - DLTR
      - WBA
      - SIRI
      - ENPH
      - ZM
      - LC
      - RIVN
      - ARM
      - APP
      - TTD
      - SMCI
      - ASML
      - AZN
  dow:
    market: Dow
    symbols:
      - AAPL
      - AMGN
      - AMZN
      - AXP
      - BA
      - CAT
      - CRM
      - CSCO
      - CVX
      - DIS
      - GS
      - HD
      - HON
      - IBM
      - JNJ
      - JPM
      - KO
      - MCD
      - MMM
      - MRK
      - MSFT
      - NKE
      - NVDA
      - PG
      - SHW
      - TRV
      - UNH
      - V
      - VZ
      - WMT
